//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestsForSimmetrics.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CHRISTOPHER PARKINSON,CHRIS PARKINSON, 0.500,0.00,0.714,0.258,0.50,0.688,0.789,0." +
            "765,0.714,0.738,0.750,0.50,0.293,0.333,0.50,1.0,0.50")]
        public string blockDistance1 {
            get {
                return ((string)(this["blockDistance1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RUTH KATHERINE LANHAM,RUTH KATHERINE PARKINSON, 0.667,0.00,0.875,0.314,0.667,0.63" +
            "4,0.638,0.651,0.708,0.792,0.612,0.667,0.423,0.500,0.667,0.80,0.667")]
        public string blockDistance2 {
            get {
                return ((string)(this["blockDistance2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SHACKLEFORD,SHACKELFORD,0.970,0.982,1.00,0.165,0.090,0.818,0.727,0.01,0.818,0.909" +
            ",0.692,0.0,0.0")]
        public string jaroName1 {
            get {
                return ((string)(this["jaroName1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DUNNINGHAM,CUNNIGHAM,0.896,0.896,0.90,0.144,0.00,0.833,0.778,0.01,0.800,0.850,0.5" +
            "22,0.0,0.0")]
        public string jaroName2 {
            get {
                return ((string)(this["jaroName2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NICHLESON,NICHULSON,0.926,0.956,1.00,0.136,0.00,0.778,0.667,0.01,0.778,0.889,0.63" +
            "6,0.0,0.0")]
        public string jaroName3 {
            get {
                return ((string)(this["jaroName3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("JONES,JOHNSON,0.790,0.832,0.714,0.093,0.00,0.600,0.400,0.01,0.429,0.571,0.250,0.0" +
            ",0.0")]
        public string jaroName4 {
            get {
                return ((string)(this["jaroName4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MASSEY,MASSIE,0.889,0.933,1.00,0.093,0.00,0.75,0.767,0.01,0.667,0.833,0.50,0.0,0." +
            "0")]
        public string jaroName5 {
            get {
                return ((string)(this["jaroName5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ABROMS,ABRAMS,0.889,0.922,1.00,0.093,0.00,0.667,0.933,0.01,0.833,0.917,0.625,0.0," +
            "0.0")]
        public string jaroName6 {
            get {
                return ((string)(this["jaroName6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("JERALDINE,GERALDINE,0.926,0.926,1.00,0.136,0.00,0.889,0.956,0.01,0.889,0.944,0.72" +
            "7,0.0,0.0")]
        public string jaroName7 {
            get {
                return ((string)(this["jaroName7"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SHACKLEFORD,SHACKELFORD,0.818,0.818,0.818,0.818")]
        public string swName1 {
            get {
                return ((string)(this["swName1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DUNNINGHAM,CUNNIGHAM,0.833,0.833,0.833,0.833")]
        public string swName2 {
            get {
                return ((string)(this["swName2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NICHLESON,NICHULSON,0.778,0.778,0.778,0.778")]
        public string swName3 {
            get {
                return ((string)(this["swName3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SHACKLEFORD,SHACKELFORD,0.727,0.727,0.727,0.727")]
        public string swgName1 {
            get {
                return ((string)(this["swgName1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DUNNINGHAM,CUNNIGHAM,0.778,0.778,0.778,0.778")]
        public string swgName2 {
            get {
                return ((string)(this["swgName2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ABROMS,ABRAMS,0.933,0.933,0.933,0.933")]
        public string swgName6 {
            get {
                return ((string)(this["swgName6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("JERALDINE,GERALDINE,0.956,0.956,0.956,0.956")]
        public string swgName7 {
            get {
                return ((string)(this["swgName7"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NICHLESON,NICHULSON,0.667,0.667,0.667,0.667")]
        public string swgName3 {
            get {
                return ((string)(this["swgName3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("JONES,JOHNSON,0.400,0.400,0.400,0.400")]
        public string swgName4 {
            get {
                return ((string)(this["swgName4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MASSEY,MASSIE,0.767,0.767,0.767,0.767")]
        public string swgName5 {
            get {
                return ((string)(this["swgName5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("JONES,JOHNSON,0.600,0.600,0.600,0.600")]
        public string swName4 {
            get {
                return ((string)(this["swName4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MASSEY,MASSIE,0.750,0.750,0.750,0.750")]
        public string swName5 {
            get {
                return ((string)(this["swName5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ABROMS,ABRAMS,0.667,0.667,0.667,0.667")]
        public string swName6 {
            get {
                return ((string)(this["swName6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("JERALDINE,GERALDINE,0.889,0.889,0.889,0.889")]
        public string swName7 {
            get {
                return ((string)(this["swName7"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SHACKLEFORD,SHACKELFORD,0.727,0.727,0.727,0.727,0.727,0.727,0.727,0.727")]
        public string swgaName1 {
            get {
                return ((string)(this["swgaName1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DUNNINGHAM,CUNNIGHAM,0.778,0.778,0.778,0.778,0.778,0.778,0.778,0.778")]
        public string swgaName2 {
            get {
                return ((string)(this["swgaName2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NICHLESON,NICHULSON,0.667,0.667,0.667,0.667,0.667,0.667,0.667,0.667")]
        public string swgaName3 {
            get {
                return ((string)(this["swgaName3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("JONES,JOHNSON,0.400,0.400,0.400,0.400,0.400,0.400,0.400,0.400")]
        public string swgaName4 {
            get {
                return ((string)(this["swgaName4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MASSEY,MASSIE,0.767,0.767,0.767,0.767,0.767,0.767,0.767,0.767")]
        public string swgaName5 {
            get {
                return ((string)(this["swgaName5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ABROMS,ABRAMS,0.933,0.933,0.933,0.933,0.933,0.933,0.933,0.933")]
        public string swgaName6 {
            get {
                return ((string)(this["swgaName6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("JERALDINE,GERALDINE,0.956,0.956,0.956,0.956,0.956,0.956,0.956,0.956")]
        public string swgaName7 {
            get {
                return ((string)(this["swgaName7"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CHRIS PARKINSON 10 ADOM COURT 61 THIKET ROAD SUTTON SM1 4PX,CHRISTOPHER lARKINSON" +
            " FLAT 10 ADAM COURT 59-61 THICKET ROAD SUTTON, 0.725, 0.725, 0.725, 0.725, 0.725" +
            ", 0.725, 0.725, 0.725, 0.725, 0.725, 0.725, 0.725, 0.725, 0.725, 0.725, 0.725")]
        public string swgaName8 {
            get {
                return ((string)(this["swgaName8"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CHRIS PARKINSON 10 ADOM COURT 61 THIKET ROAD SUTTON SM1 4PX,CHRISTOPHER lARKINSON" +
            " FLAT 10 ADAM COURT 59-61 THICKET ROAD SUTTON, 0.381, 0.0, 0.894, 0.684, 0.381, " +
            "0.612, 0.693, 0.699, 0.621, 0.644, 0.605, 0.381, 0.213, 0.235, 0.364, 0.860,0.40" +
            "")]
        public string blockDistance3 {
            get {
                return ((string)(this["blockDistance3"]));
            }
            set {
                this["blockDistance3"] = value;
            }
        }
    }
}
